schema_version = "1.0.0"

id = "imeshh_toolbox"
version = "1.0.0"
name = "iMeshh Toolbox"
tagline = "A collection of utility scripts for Blender by iMeshh"
maintainer = "Kris / iMeshh <kris@imeshh.com>"
type = "add-on"

website = "https://github.com/krisimeshh/iMeshhScripts"

tags = ["3D View"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
